import { StyleSheet } from 'react-native';

export const bookingStyles = StyleSheet.create({
  fullScreenContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  content: {
    flex: 1,
  },
  formBox: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 24,
  },
  formTitle: {
    fontSize: 24,
    fontWeight: '600',
    marginBottom: 24,
    color: '#333',
    textAlign: 'center',
  },
  formLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6C4DF6',
    marginBottom: 2,
  },
  formValue: {
    fontSize: 16,
    color: '#222',
    marginBottom: 2,
  },
  input: {
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    fontSize: 16,
    backgroundColor: '#faf9ff',
  },
  dateButton: {
  borderWidth: 1,
  borderColor: '#eee',
  borderRadius: 8,
  padding: 12,
  backgroundColor: '#faf9ff',
  width: '100%',
  },
  dateButtonText: {
    fontSize: 16,
    color: '#333',
  },
  buttonContainer: {
    flexDirection: 'row',
    marginTop: 32,
    paddingTop: 24,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#f8f8f8',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#666',
    fontWeight: '600',
    fontSize: 16,
  },
  submitButton: {
    flex: 2,
    backgroundColor: '#5A4FCF',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  confirmationContainer: {
    flex: 1,
    padding: 24,
  },
  confirmationCard: {
    alignItems: 'center',
    paddingTop: 40,
    paddingBottom: 40,
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    borderRadius: 16,
    marginBottom: 24,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  confirmationHeader: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#5A4FCF',
  },
  brandText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#5A4FCF',
    letterSpacing: 2,
  },
  confirmationDate: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  successIconText: {
    fontSize: 40,
    color: '#fff',
    fontWeight: 'bold',
  },
  confirmationTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 8,
  },
  confirmationSubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 32,
  },
  bookingDetails: {
    width: '100%',
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 20,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  detailRowNoBorder: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 0,
  },
  detailLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#495057',
    flex: 1,
  },
  detailValue: {
    fontSize: 16,
    color: '#212529',
    flex: 2,
    textAlign: 'right',
  },
  confirmationButtons: {
    flexDirection: 'row',
    width: '100%',
  },
  saveButton: {
    flex: 1,
    backgroundColor: '#6c757d',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  doneButton: {
    flex: 1,
    backgroundColor: '#5A4FCF',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  doneButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  // Compact layout additions for booking form
  inputRow: {
  flexDirection: 'row',
  marginBottom: 12,
  },
  inputHalf: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#eee',
    backgroundColor: '#faf9ff',
    padding: 12,
    fontSize: 16,
  },
  inputLeft: {
  borderTopLeftRadius: 12,
  borderBottomLeftRadius: 12,
  borderTopRightRadius: 0,
  borderBottomRightRadius: 0,
  marginRight: 8,
  },
  inputRight: {
  borderTopRightRadius: 12,
  borderBottomRightRadius: 12,
  borderTopLeftRadius: 0,
  borderBottomLeftRadius: 0,
  marginLeft: 0,
  },
  datesSection: {
    marginTop: 8,
    marginBottom: 16,
  },
  formValueHint: {
    color: '#666',
    fontStyle: 'italic',
    marginBottom: 8,
    fontSize: 15,
  },
  dateRow: {
  flexDirection: 'row',
  alignItems: 'stretch',
  marginTop: 4,
  marginBottom: 4,
  },
  dateCol: {
    flex: 1,
    alignItems: 'stretch',
  },
  getLocationButton: {
    marginTop: 20,
    backgroundColor: '#5A4FCF',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  getLocationButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.5,
  },
});
